### PR TITLE
Remove all clothes button

### PR DESCRIPTION
**Pull request by AnugrahHu**
```
ws = Game.GetWardrobeSystem() 
itemids = ws:GetStoredItemIDs()
for _,itemid in pairs(itemids) do 
 ws:ForgetItemID(itemid) 
end
```
Added a remove all clothes button using the above ForgetItemID function, and removed the old warning.

### CODE REVIEW

**Comment by MrSimbax** [comment]
I was excited to try this out, but it doesn't work :( Patch 2.02, no other mods installed other than CET and Wardrobe Items Adder.

```
[2023-10-29 08:19:52 UTC+01:00] [996] init.lua:169: attempt to call method 'ForgetItemID' (a nil value)
stack traceback:
	init.lua:169: in function 'removeAllClothesFromWardrobe'
	...ins\cyber_engine_tweaks\mods\wardrobe_items_adder\ui.lua:119: in function 'drawMainTab'
	...ins\cyber_engine_tweaks\mods\wardrobe_items_adder\ui.lua:93: in function 'onDraw'
	init.lua:267: in function <init.lua:263>
```

May I ask how did you find `ForgetItemID` function? I can't find it in [here](https://codeberg.org/adamsmasher/cyberpunk/src/commit/20e2051921152b83f1daa57ecadf7f3b3288cf8e/core/systems/wardrobeSystem.swift). Do you have other mods installed? Perhaps one of them extended WardrobeSystem with this feature. If yes, I'm curious how they implemented it.

**Comment by MrSimbax** [comment]
Ok, I think I've found the mod: https://github.com/psiberx/cp2077-codeware/wiki#managing-wardrobe Thank you for the hint!

I guess this would make Codeware required as dependency. I think it should be optional though, because not all users will want to remove clothes. I'll wait with merging this for now and do some more testing.

**Comment by AnugrahHu** [comment]
Ahh, alright I was using it fully modded so that's why it worked right away for me, sorry for the false hope. At the very least now you know it's possible!

**Comment by MrSimbax** [comment]
Unfortunately, I cannot merge this yet. After some testing, it sometimes works, and sometimes doesn't.

From what I debugged so far, it seems ForgetItemID indeed removes items from the WardrobeSystem, as StoredItemIDs array is completely empty after pressing the button. However, after opening the wardrobe, V becomes naked, as to be expected I guess after removing _all_ the clothes, but the removed items are still on the grid, and can even be equipped again. Equipping them, however, turns out to be only temporary, as once out of the wardrobe screen, V is naked again, as if the outfit didn't save properly.

I suspect the UI state becomes inconsistent with the wardrobe system's state. I guess the game's UI code doesn't consider the possibility that items may be removed. Perhaps something like "UI:Refresh()" is needed after item removal, or something more complex is going on.

Anyway, this PR is a step in the right direction, but the final solution clearly requires more work.

**Comment by AnugrahHu** [comment]
Yep, I'll give this repo a follow and hope you'll find the final solution! I'll just coast along for now with my janky patches lol.

edit: After checking without other mods, the removal only works properly after a save-and-load. EqEX, on the other hand, always pulls from StoredItemIDs so it's fine to use with the patch (they also have a single item forget/discard which reloads the grid). Maybe have a look from there! I'll also try to fix the jank if I can...

**Comment by MrSimbax** [comment]
I think I discovered what's happening but couldn't figure out a fix. I [reported](https://github.com/psiberx/cp2077-codeware/issues/10) the issue to the author of Codeware.

Edit: I have only now noticed the edit, as GitHub doesn't give notifications for edits. Yeah, Eq-EX uses their own UI, and it uses GetStoredItemIDs which doesn't have the issue. The base game uses GetFilteredInventoryItemsData which unfortunately still has the removed item.

**Comment by AnugrahHu** [comment]
```lua
        Override('WardrobeSystem','GetFilteredInventoryItemsData', function(self, equipmentArea)
            local result = {}

            local inventoryManager = InventoryDataManagerV2:new();
            inventoryManager:Initialize(Game.GetPlayer());

            local itemIds = self:GetFilteredStoredItemIDs(equipmentArea)
            for _,itemId in pairs(itemIds) do
                table.insert(result,inventoryManager:GetInventoryItemDataFromItemID(itemId))
            end
            return result
        end)
```
Added this override function to use the GetFilteredStoredItemIDs instead if you are willing to review it again. Hopefully, it works and won't have too much side effects.

**Comment by MrSimbax** [comment]
Smart :D Seems to work, the currently equipped clothes are a little buggy until they refresh somehow, but I can live with that. In case the issue with ForgetItemID is fixed in Codeware at some point in the future, this workaround should be removed though.

The change will be in the next release, but I would like to make some other improvements first (not giving an ETA though). You will be credited in the mod's description and the changelog of course. Thanks!

**Comment by AnugrahHu** [comment]
Thank you! I think I'm getting much too used to getting a bit of jank in my results to notice lol. And yeah, hopefully Codeware will make it so that a workaround isn't needed, but I hope this will do for now. Good luck with your improvements and thanks for the mod in the first place!

**Pull request merged**
